### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by billccn** [webjars/jsx-requirejs-plugin#2]
Three problems:

1. This package uses the module name jsx-requirejs-plugin, but as it is being used as a loader plugin, "jsx-requirejs-plugin!" will have to be used in user code which is very unfriendly. Should call the plug-in "jsx" in the config.

2. The path points to main.js which is the main file for the demo and irrelevant as a webjar. It should point to jsx.js.

3. The jsx file has a dependency on the 'text' module which is called requirejs-text in webjars. I am not sure whether this should be attributed to the requirejs-text instead.

**Comment by jamesward** [comment]
How does this look: https://github.com/webjars/jsx-requirejs-plugin/pull/3

**Comment by billccn** [comment]
Amost there. but as said in point 3 above, the original jsx source refers to the 'text' module which is  exported as 'requirejs-text' in webjars. This either needs to be patched in the requirejs-text project or somehow overriden here.
The fix to the jsx bit worked as expected, so thanks!

**Comment by jamesward** [comment]
Ok, check it now.
